---

- name: Install ntp
  apt: name=ntp state=latest update_cache=true
  tags:
    - ntp

- name: Configure ntp
  template: src=ntp.conf.j2 dest=/etc/ntp.conf
  notify:
    - restart ntp
  tags:
    - ntp
