---

- name: Add nginx host files
  template: src=../../templates/symfony/nginx.conf.j2 dest=/etc/nginx/conf.d/{{ website.domain }}.conf owner=root mode=644
  notify: restart nginx
  tags:
    - website
    - symfony

- name: Create a new symfony secret token
  shell: echo $(pwgen -Bs 20 1)
  register: symfony_secret_token
  tags:
    - website
    - symfony

- name: Define symfony parameters
  template: src=../../templates/symfony/parameters.yml.j2 dest={{ website_dir }}/{{ version }}/app/config/parameters.yml
  tags:
    - website
    - symfony
