---

- name: Add nginx host files
  template: src=nginx.conf.j2 dest=/etc/nginx/conf.d/{{ item.domain }}.conf owner=root mode=644
  with_items: websites
  when: domain is not defined or domain == item.domain
  notify: restart nginx
  tags:
    - website

- name: Add php-fpm pool files
  template: src=php-fpm.conf.j2 dest=/etc/php5/fpm/pool.d/{{ item.domain }}.conf owner=root mode=644
  with_items: websites
  when: domain is not defined or domain == item.domain
  notify: restart php-fpm
  tags:
    - website

- name: Clone repositories
  git: repo={{ item.git }} dest=/var/www/{{ item.domain }} version={{ item.version | default('master') }} update=yes accept_hostkey=yes
  with_items: websites
  when: item.git is defined and (domain is not defined or domain == item.domain)
  tags:
    - website
    - deploy

- name: Launch composer dependencies
  shell: cd /var/www/{{ item.domain }}/ && [ -e "composer.json" ] && composer install -o -q || echo "No dependencies found."
  with_items: websites
  when: domain is not defined or domain == item.domain
  sudo: yes
  tags:
    - website
    - deploy

- name: Install npm dependencies
  shell: cd /var/www/{{ item.domain }}/ && [ -e "package.json" ] && npm install -o || echo "No dependencies found."
  with_items: websites
  when: domain is not defined or domain == item.domain
  tags:
    - website
    - deploy

- name: Install bower dependencies
  shell: cd /var/www/{{ item.domain }}/ && [ -e "bower.json" ] && bower install --allow-root ./ || echo "No dependencies found."
  with_items: websites
  when: domain is not defined or domain == item.domain
  tags:
    - website
    - deploy

- name: Execute grunt files
  shell: cd /var/www/{{ item.domain }}/ && [ -e "Gruntfile.json" ] && LANG=en_US.UTF-8 grunt -o || echo "No grunt file found."
  with_items: websites
  when: domain is not defined or domain == item.domain
  tags:
    - website
    - deploy

- name: Apply good rights for dev environment
  shell: cd /var/www/ && chmod -R 775 {{ item.domain }}/ && chown -R vagrant:www-data {{ item.domain }}/
  with_items: websites
  when: env == 'dev' and (domain is not defined or domain == item.domain)
  tags:
    - website
    - deploy

- name: Apply good rights for others environments
  shell: cd /var/www/ && chmod -R 775 {{ item.domain }}/ && chown -R vagrant:www-data {{ item.domain }}/
  with_items: websites
  when: env != 'dev' and (domain is not defined or domain == item.domain)
  tags:
    - website
    - deploy
