---

- set_fact: user="www-data"
  when: env != 'dev'

- set_fact: user="vagrant"
  when: env == 'dev'

- name: Define other variables
  set_fact: 
    website_dir: "{{ web_directory }}{{ website.domain }}"
    version: "{{ website.version | default('master') }}"
    type: "{{ website.type|default('other') }}"

- name: Start new deployment
  debug: msg="{{ website }}"

- name: Add nginx host files
  template: src=nginx.conf.j2 dest=/etc/nginx/conf.d/{{ website.domain }}.conf owner=root mode=644
  notify: restart nginx

- name: Add php-fpm pool files
  template: src=php-fpm.conf.j2 dest=/etc/php5/fpm/pool.d/{{ website.domain }}.conf owner=root mode=644
  notify: restart php-fpm

- name: Check if site directory exists
  stat: path={{ website_dir }}
  register: check_path

- name: It doesn't so we create it
  file: dest={{ website_dir }} owner={{ user }} group=www-data state=directory
  when: check_path.stat.exists == false

- name: Clone repository
  git: repo={{ website.git }} dest={{ website_dir }}/{{ version }} version={{ version }} update=yes accept_hostkey=yes
  when: website.git is defined

- name: Launch composer dependencies
  shell: cd {{ website_dir }}/{{ version }} && [ -e "composer.json" ] && composer install -o -q || echo "No dependencies found."
  sudo: yes

- name: Install npm dependencies
  shell: cd {{ website_dir }}/{{ version }} && [ -e "package.json" ] && npm install -o || echo "No dependencies found."

- name: Install bower dependencies
  shell: cd {{ website_dir }}/{{ version }} && [ -e "bower.json" ] && bower install --allow-root ./ || echo "No dependencies found."

- name: Execute grunt files
  shell: cd {{ website_dir }}/{{ version }} && [ -e "Gruntfile.json" ] && LANG=en_US.UTF-8 grunt -o || echo "No grunt file found."

- include: symfony.yml
  when: type == 'symfony'

- name: Check if web directory exists
  stat: path={{ website_dir }}/{{ version }}/{{ website.web_dir | default('web') }}
  register: check_web_path

- name: Create version file
  template: src=version.txt.j2 dest={{ website_dir }}/{{ version }}/{{ website.web_dir | default('web') }}/version.txt owner={{ user }} group=www-data
  when: check_web_path.stat.exists == true

# - name: Apply good rights
#   shell: cd {{ website_dir }} && chmod -R 775 {{ version }}/ && chown -R {{ user }}:www-data {{ version }}/

- name: Change release folder
  file: src={{ website_dir }}/{{ version }} dest={{ website_dir }}/release owner={{ user }} group=www-data state=link
  notify: restart php-fpm

- include: right.yml
