---

- name: Create a new symfony secret token
  shell: echo $(pwgen -Bs 20 1)
  register: symfony_secret_token

- name: Define symfony parameters
  template: src=symfony.parameters.yml.j2 dest=/var/www/{{ item.domain }}/{{ item.version | default('master') }}/app/config/parameters.yml
  when: (domain is not defined or domain == item.domain) and item.type|default(false) == 'symfony'
  with_items: websites