---

- name: Create a new symfony secret token
  shell: echo $(pwgen -Bs 20 1)
  register: symfony_secret_token

- name: Define symfony parameters
  template: src=symfony.parameters.yml.j2 dest={{ website_dir }}/{{ version }}/app/config/parameters.yml
