---

- name: Add node.js repository
  apt_repository: repo='ppa:chris-lea/node.js'
  tags:
    - nodejs

- name: Install required packages
  apt: pkg={{ item }} state=latest update_cache=yes
  with_items:
    - nodejs
    - build-essential
  tags:
    - nodejs
