---

- name: Install git
  apt: name=git state=latest update_cache=true
  tags:
    - git

- name: Prevent against firewalls/proxies security
  shell: git config --global url."https://".insteadOf git://
  tags:
    - git