---

- name: Add nginx key
  apt_key: url=http://nginx.org/keys/nginx_signing.key state=present
  tags:
    - nginx

- name: Add nginx repository
  apt_repository: repo='deb http://nginx.org/packages/ubuntu trusty nginx'
  tags:
    - nginx

- name: Add nginx repository
  apt_repository: repo='deb-src http://nginx.org/packages/ubuntu trusty nginx' update_cache=yes
  tags:
    - nginx

- name: Install nginx
  apt: name=nginx state=latest update_cache=true
  tags:
    - webserver
    - nginx

- name: Update nginx configuration
  copy: src=fuliculi.conf dest=/etc/nginx/conf.d/fuliculi.conf
  tags:
    - webserver
    - nginx

- name: Config common ssl files
  template: src=fuliculi-ssl.conf.j2 dest=/etc/nginx/conf.d/fuliculi-ssl.conf
  when: ssl is defined
  tags:
    - webserver
    - nginx

- name: Define new default index file
  copy: src=default.html dest=/usr/share/nginx/html/index.html
  tags:
    - webserver
    - nginx

- name: insert iptables rule for httpd
  lineinfile: "dest=/etc/iptables.rules state=present regexp='{{ httpd_port }}' insertafter='# CUSTOM RULES HERE' line='-A INPUT -p tcp --dport {{ httpd_port }} -j ACCEPT'"
  tags:
    - webserver
    - nginx
    - firewall
  notify: restart firewall