---

- name: Add nginx key
  apt_key: url=http://nginx.org/keys/nginx_signing.key state=present
  tags:
    - nginx

- name: Add nginx repository
  apt_repository: repo='deb http://nginx.org/packages/ubuntu trusty nginx'
  tags:
    - nginx

- name: Add nginx repository
  apt_repository: repo='deb-src http://nginx.org/packages/ubuntu trusty nginx' update_cache=yes
  tags:
    - nginx

- name: Install nginx
  apt: name=nginx state=latest update_cache=true
  tags:
    - nginx

- name: Update nginx configuration
  template: src=nginx.conf.j2 dest=/etc/nginx/conf.d/{{ item.key }}.conf
  with_dict: nginx
  tags:
    - nginx

- name: Config common ssl files
  template: src=ssl.conf.j2 dest=/etc/nginx/conf.d/ssl.conf
  when: ssl is defined
  tags:
    - nginx

- name: Define new default index file
  copy: src=default.html dest=/usr/share/nginx/html/index.html
  tags:
    - nginx

- name: "Insert iptables rule for http & https"
  lineinfile: "dest=/etc/iptables.rules state=present regexp='{{ item }}' insertafter='# CUSTOM RULES HERE' line='-A INPUT -p tcp --dport {{ item }} -j ACCEPT'"
  with_items:
    - standard_port
    - ssl_port
  tags:
    - nginx
    - firewall
  notify: restart firewall