---

- name: Configure locales
  hosts: all
  user: vagrant
  sudo: yes

  roles:
    - locales

- name: Configure firewall
  hosts: all
  user: vagrant
  sudo: yes

  roles:
    - iptables
    - fail2ban
    - logwatch

- name: Time synchronization
  hosts: all
  user: vagrant
  sudo: yes

  roles:
    - ntp
    - timezone

- name: Source control management
  hosts: all
  user: vagrant
  sudo: yes

  roles:
    - git

- name: Password management
  hosts: all
  user: vagrant
  sudo: yes

  roles:
    - pwgen

- name: Tools management
  hosts: all
  user: vagrant
  sudo: yes

  roles:
    - supervisor