---

- include: common.yml

- name: Install webserver
  hosts: webserver
  user: vagrant
  sudo: yes

  roles:
    - php
    - nginx
    - rabbitmq

- name: Tools to build applications
  hosts: webserver
  user: vagrant
  sudo: yes

  roles:
    - nodejs
    - grunt
