---

- include: common.yml

- name: Install webserver
  hosts: webserver
  user: vagrant
  sudo: yes

  roles:
    - php
    - nginx
    - rabbitmq
    - { role: samba, when: "env == 'dev'" }

- name: Install elasticsearch
  hosts: webserver
  user: vagrant
  sudo: yes

  roles:
    - elasticsearch

- name: Tools to build applications
  hosts: webserver
  user: vagrant
  sudo: yes

  roles:
    - composer
    - nodejs
    - grunt
    - bower
    - { role: yeoman, when: "env == 'dev'" }

- name: Install websites
  hosts: webserver
  user: vagrant
  sudo: yes

  roles:
    - { role: website, tags: ["website", "api"], website: "{{ websites['api'] }}" }
    - { role: website, tags: ["website", "fuliculi"], website: "{{ websites['fuliculi'] }}" }